# Generated by Django 5.0.3 on 2024-03-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_tracking', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
    ]
